[package]
name = "CoinDeployer"
version = "1.0.0"
authors = []

[addresses]
bapt_framework = "c1f80cf284c8db6a1c03ad29bc93d6cdc10e61ff39ffd24c66fb51dfbacfbe49"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
