[package]
name = "CoinDeployer"
version = "1.0.1"
authors = []

[addresses]
bapt_framework = "a55a7122aa085e4bf34b755675fb900c40ee92f60c068255609ecea8ef4123f3"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
